name: pykasso2D
channels:
  - agd-lbr
  - conda-forge
  - defaults
dependencies:
  - agd=0.1.29=py_0
  - anyio=3.6.1=py39hcbf5309_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39hb82d6ee_2
  - asttokens=2.0.5=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - babel=2.10.3=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - bleach=5.0.0=pyhd8ed1ab_0
  - brotli=1.0.9=h8ffe710_7
  - brotli-bin=1.0.9=h8ffe710_7
  - brotlipy=0.7.0=py39hb82d6ee_1004
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2022.6.15=h5b45459_0
  - certifi=2022.6.15=py39hcbf5309_0
  - cffi=1.15.0=py39h0878f49_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - cryptography=37.0.2=py39h7bc7c5c_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.6.0=py39h415ef7b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - et_xmlfile=1.0.1=py_1001
  - executing=0.8.3=pyhd8ed1ab_0
  - ffmpeg=4.3.1=ha925a31_0
  - flit-core=3.7.1=pyhd8ed1ab_0
  - fonttools=4.33.3=py39hb82d6ee_0
  - freetype=2.10.4=h546665d_1
  - gettext=0.19.8.1=ha2e2712_1008
  - glib=2.70.2=h7755175_4
  - glib-tools=2.70.2=h7755175_4
  - gst-plugins-base=1.20.3=he07aa86_0
  - gstreamer=1.20.3=hdff456e_0
  - hfm=0.2.13=py3.9
  - icu=70.1=h0e60522_0
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py39hcbf5309_0
  - importlib_metadata=4.11.4=hd8ed1ab_0
  - importlib_resources=5.8.0=pyhd8ed1ab_0
  - intel-openmp=2022.1.0=h57928b3_3787
  - ipykernel=6.15.0=pyh025b116_0
  - ipython=8.4.0=py39hcbf5309_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.7.0=pyhd8ed1ab_0
  - jedi=0.18.1=py39hcbf5309_1
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h8ffe710_1
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.6.0=pyhd8ed1ab_0
  - jupyter=1.0.0=py39hcbf5309_7
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_console=6.4.3=pyhd8ed1ab_0
  - jupyter_core=4.10.0=py39hcbf5309_0
  - jupyter_server=1.17.1=pyhd8ed1ab_0
  - jupyterlab=3.4.3=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.14.0=pyhd8ed1ab_0
  - jupyterlab_widgets=1.1.0=pyhd8ed1ab_0
  - kiwisolver=1.4.3=py39h2e07f2f_0
  - krb5=1.19.3=h1176d77_0
  - lcms2=2.12=h2a16943_0
  - lerc=3.0=h0e60522_0
  - libblas=3.9.0=15_win64_mkl
  - libbrotlicommon=1.0.9=h8ffe710_7
  - libbrotlidec=1.0.9=h8ffe710_7
  - libbrotlienc=1.0.9=h8ffe710_7
  - libcblas=3.9.0=15_win64_mkl
  - libclang=14.0.5=default_h77d9078_0
  - libclang13=14.0.5=default_h77d9078_0
  - libdeflate=1.12=h8ffe710_0
  - libffi=3.4.2=h8ffe710_5
  - libglib=2.70.2=h3be07f2_4
  - libiconv=1.16=he774522_0
  - liblapack=3.9.0=15_win64_mkl
  - libogg=1.3.4=h8ffe710_1
  - libpng=1.6.37=h1d00b33_2
  - libsodium=1.0.18=h8d14728_1
  - libtiff=4.4.0=h2ed3b44_1
  - libvorbis=1.3.7=h0e60522_0
  - libwebp=1.2.2=h57928b3_0
  - libwebp-base=1.2.2=h8ffe710_1
  - libxcb=1.13=hcd874cb_1004
  - libzlib=1.2.12=h8ffe710_1
  - lz4-c=1.9.3=h8ffe710_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.1.1=py39hb82d6ee_1
  - matplotlib=3.5.2=py39hcbf5309_0
  - matplotlib-base=3.5.2=py39h581301d_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py39hb82d6ee_1005
  - mkl=2022.1.0=h6a75c08_874
  - mplstereonet=0.6.2=pyhd8ed1ab_0
  - mpmath=1.2.1=pyhd8ed1ab_0
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclassic=0.3.7=pyhd8ed1ab_0
  - nbclient=0.6.4=pyhd8ed1ab_1
  - nbconvert=6.5.0=pyhd8ed1ab_0
  - nbconvert-core=6.5.0=pyhd8ed1ab_0
  - nbconvert-pandoc=6.5.0=pyhd8ed1ab_0
  - nbformat=5.4.0=pyhd8ed1ab_0
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - networkx=2.8.4=pyhd8ed1ab_0
  - notebook=6.4.12=pyha770c72_0
  - notebook-shim=0.1.0=pyhd8ed1ab_0
  - numpy=1.22.4=py39h0948cea_0
  - openjpeg=2.4.0=hb211442_1
  - openpyxl=3.0.9=pyhd8ed1ab_0
  - openssl=1.1.1o=h8ffe710_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.2=py39h2e25243_2
  - pandoc=2.18=h57928b3_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=h0e60522_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.1.1=py39ha53f419_1
  - pip=22.1.2=pyhd8ed1ab_0
  - plotly=5.8.2=pyhd8ed1ab_0
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.29=pyha770c72_0
  - prompt_toolkit=3.0.29=hd8ed1ab_0
  - psutil=5.9.1=py39hb82d6ee_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.12.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.4=py39hb08f45d_1
  - pyqt5-sip=12.9.0=py39h415ef7b_1
  - pyrsistent=0.18.1=py39hb82d6ee_1
  - pysocks=1.7.1=py39hcbf5309_5
  - python=3.9.13=h9a09f29_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.15.3=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2022.1=pyhd8ed1ab_0
  - pywin32=303=py39hb82d6ee_0
  - pywinpty=2.0.5=py39h99910a6_1
  - pyyaml=6.0=py39hb82d6ee_4
  - pyzmq=23.1.0=py39he46f08e_0
  - qt-main=5.15.4=h467ea89_2
  - qtconsole=5.3.1=pyhd8ed1ab_0
  - qtconsole-base=5.3.1=pyha770c72_0
  - qtpy=2.1.0=pyhd8ed1ab_0
  - requests=2.28.0=pyhd8ed1ab_0
  - scikit-fmm=2022.3.26=py39h2e25243_1
  - scipy=1.8.1=py39hc0c34ad_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=62.5.0=py39hcbf5309_0
  - sip=6.5.1=py39h415ef7b_2
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.2.0=py39hcbf5309_3
  - soupsieve=2.3.1=pyhd8ed1ab_0
  - sqlite=3.38.5=h8ffe710_0
  - stack_data=0.3.0=pyhd8ed1ab_0
  - tbb=2021.5.0=h2d74725_1
  - tenacity=8.0.1=pyhd8ed1ab_0
  - terminado=0.15.0=py39hcbf5309_0
  - tinycss2=1.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h8ffe710_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.1=py39hb82d6ee_3
  - traitlets=5.3.0=pyhd8ed1ab_0
  - tzdata=2022a=h191b570_0
  - ucrt=10.0.20348.0=h57928b3_0
  - unicodedata2=14.0.0=py39hb82d6ee_1
  - urllib3=1.26.9=pyhd8ed1ab_0
  - vc=14.2=hb210afc_6
  - vs2015_runtime=14.29.30037=h902a5da_6
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.3.2=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=3.6.0=py39hcbf5309_0
  - win_inet_pton=1.1.0=py39hcbf5309_4
  - winpty=0.4.3=4
  - xlrd=2.0.1=pyhd8ed1ab_3
  - xorg-libxau=1.0.9=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.5=h62dcd97_1
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.12=h8ffe710_1
  - zstd=1.5.2=h6255e5f_1
  - pip:
    - karstnet==1.2.0
prefix: C:\Users\cfandel\Anaconda3\envs\pykasso2D
